import { createContext, useState, useEffect, useContext } from 'react';
import { base44 } from '@/api/base44Client';

export const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home', features: 'Features', servers: 'Servers', pricing: 'Pricing',
    support: 'Support', logIn: 'Log In', signUp: 'Sign Up', choosePlan: 'Choose a Plan',
    heroTitle: 'Your Privacy. Fully Protected.',
    heroSubtitle: 'VoxVPN shields your identity with military-grade encryption, a strict no-logs policy, and blazing-fast servers in 60+ countries.',
    getVoxvpn: 'Get VoxVPN Now', seeHowItWorks: 'See How It Works',
    questionsContact: 'Questions? Contact us →',
    trustNoLogs: 'No-Logs Policy', trustAES: 'AES-256 Encryption', trustLocations: '60+ Locations',
    trustKillSwitch: 'Kill Switch', trustMoneyBack: '30-Day Money-Back', trustSupport: '24/7 Support',
    vpnStatusCard: 'VPN Status Card', protected: 'Protected', disconnect: 'Disconnect', founded: 'Founded 2020',
    footerTagline: 'Your privacy is our priority. Stay protected, stay unrestricted.',
    weAccept: 'We Accept', followUs: 'Follow Us',
    footerRights: '© 2026 VoxDigits Communications LLC. All rights reserved. www.voxvpn.net',
    footerAbout: 'About', footerContact: 'Contact', footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms', footerRefund: 'Refund Policy', footerCookie: 'Cookie Policy',
    aiAssistant: 'AI Assistant',
    whyVoxvpn: 'Why VoxVPN', featuresTitle1: 'Everything you need.', featuresTitle2: "Nothing you don't.",
    featuresSubtitle: 'Every feature is designed with one goal: keeping you private, safe, and unrestricted online.',
    readyProtected: 'Ready to get protected?', joinUsers: 'Join 2,500+ users who trust VoxVPN. Plans start at $2.49/mo.', viewPlans: 'View Plans →',
    statServers: 'VPN Servers', statServersSub: 'across the globe', statCountries: 'Countries', statCountriesSub: 'server locations worldwide',
    statCustomers: 'Active Customers', statCustomersSub: 'protected worldwide', statUptime: 'Uptime SLA', statUptimeSub: 'guaranteed reliability',
    globalNetwork: 'Global Network', serversTitle1: 'Servers on Every', serversTitle2: ' Continent',
    serversSubtitle: 'Connect through our high-speed infrastructure in 20 locations across 4 continents. Every server runs VoxVPN with AES-256 encryption.',
    totalServers: 'Total Servers', onlineNow: 'Online Now', locationsLabel: 'Locations', uptimeLabel: 'Uptime',
    loadingNetwork: 'Loading live server network…', loadingMap: 'Loading map…', regionLocations: 'locations', moreLabel: 'more',
    pricingLabel: 'Pricing', pricingTitle: 'Simple, Transparent Pricing',
    pricingSubtitle: 'All plans include AES-256 encryption and a strict no-logs policy. Cancel anytime.',
    pricesIn: 'Prices shown in', detectedLabel: 'Detected:',
    liveSupport: 'Live, 24-hour customer support',
    liveSupportDesc: "Real support from real people. We're available through instant live chat and email to help you set up and troubleshoot.",
    contactSupport: 'Contact Support →', moneyBackTitle: '30-day money-back guarantee',
    moneyBackDesc: "Our VPN is easy to use. So is our guarantee. If you're not satisfied, just ask Support for a full refund. No hassle, no risk.",
    getVoxvpnCta: 'Get VoxVPN →', securePayment: 'Secure Payment by Stripe', pciCompliant: 'PCI-DSS Compliant',
    pricingFooter: 'All prices auto-converted to your local currency ({code}). 30-day money-back guarantee. Secure payment via Stripe · Hubtel · Alipay · WeChat Pay.',
    reviewsBadge: '4.9 / 5 — 12,000+ REVIEWS', testimonialsTitle: 'Loved by Users Worldwide',
    testimonialsSubtitle: 'Join thousands of satisfied customers who trust VoxVPN to protect their privacy every day.',
    trustedSecure: 'Trusted & Secure', trustedSubtitle: 'Privacy-first infrastructure, built to keep you protected',
  },
  es: {
    home: 'Inicio', features: 'Características', servers: 'Servidores', pricing: 'Precios',
    support: 'Soporte', logIn: 'Iniciar sesión', signUp: 'Registrarse', choosePlan: 'Elegir un plan',
    heroTitle: 'Tu Privacidad. Totalmente Protegida.',
    heroSubtitle: 'VoxVPN protege tu identidad con cifrado de grado militar, una estricta política de no registro y servidores ultrarrápidos en más de 60 países.',
    getVoxvpn: 'Obtén VoxVPN Ahora', seeHowItWorks: 'Ver Cómo Funciona',
    questionsContact: '¿Preguntas? Contáctanos →',
    trustNoLogs: 'Sin Registros', trustAES: 'Cifrado AES-256', trustLocations: '60+ Ubicaciones',
    trustKillSwitch: 'Interruptor de Apagado', trustMoneyBack: '30 Días de Garantía', trustSupport: 'Soporte 24/7',
    vpnStatusCard: 'Tarjeta de Estado VPN', protected: 'Protegido', disconnect: 'Desconectar', founded: 'Fundada 2020',
    footerTagline: 'Tu privacidad es nuestra prioridad. Mantente protegido, mantente sin restricciones.',
    weAccept: 'Aceptamos', followUs: 'Síguenos',
    footerRights: '© 2026 VoxDigits Communications LLC. Todos los derechos reservados. www.voxvpn.net',
    footerAbout: 'Acerca de', footerContact: 'Contacto', footerPrivacy: 'Política de Privacidad',
    footerTerms: 'Términos', footerRefund: 'Política de Reembolso', footerCookie: 'Política de Cookies',
    aiAssistant: 'Asistente IA',
    whyVoxvpn: 'Por qué VoxVPN', featuresTitle1: 'Todo lo que necesitas.', featuresTitle2: 'Nada que no necesites.',
    featuresSubtitle: 'Cada función está diseñada con un objetivo: mantenerte privado, seguro y sin restricciones en línea.',
    readyProtected: '¿Listo para estar protegido?', joinUsers: 'Únete a más de 2.500 usuarios que confían en VoxVPN. Planes desde $2.49/mes.', viewPlans: 'Ver Planes →',
    statServers: 'Servidores VPN', statServersSub: 'en todo el mundo', statCountries: 'Países', statCountriesSub: 'ubicaciones de servidores en todo el mundo',
    statCustomers: 'Clientes Activos', statCustomersSub: 'protegidos en todo el mundo', statUptime: 'SLA de Disponibilidad', statUptimeSub: 'fiabilidad garantizada',
    globalNetwork: 'Red Global', serversTitle1: 'Servidores en Cada', serversTitle2: ' Continente',
    serversSubtitle: 'Conéctate a través de nuestra infraestructura de alta velocidad en 20 ubicaciones en 4 continentes. Cada servidor ejecuta VoxVPN con cifrado AES-256.',
    totalServers: 'Servidores Totales', onlineNow: 'En Línea Ahora', locationsLabel: 'Ubicaciones', uptimeLabel: 'Disponibilidad',
    loadingNetwork: 'Cargando red de servidores en vivo…', loadingMap: 'Cargando mapa…', regionLocations: 'ubicaciones', moreLabel: 'más',
    pricingLabel: 'Precios', pricingTitle: 'Precios Simples y Transparentes',
    pricingSubtitle: 'Todos los planes incluyen cifrado AES-256 y una estricta política de no registro. Cancela cuando quieras.',
    pricesIn: 'Precios en', detectedLabel: 'Detectado:',
    liveSupport: 'Soporte al cliente en vivo, 24 horas',
    liveSupportDesc: 'Soporte real de personas reales. Estamos disponibles por chat en vivo y correo electrónico para ayudarte a configurar y solucionar problemas.',
    contactSupport: 'Contactar Soporte →', moneyBackTitle: 'Garantía de devolución de 30 días',
    moneyBackDesc: 'Nuestro VPN es fácil de usar. Al igual que nuestra garantía. Si no estás satisfecho, solo pide a Soporte un reembolso completo. Sin complicaciones, sin riesgo.',
    getVoxvpnCta: 'Obtener VoxVPN →', securePayment: 'Pago Seguro por Stripe', pciCompliant: 'Cumple con PCI-DSS',
    pricingFooter: 'Todos los precios se convierten a tu moneda local ({code}). Garantía de devolución de 30 días. Pago seguro vía Stripe · Hubtel · Alipay · WeChat Pay.',
    reviewsBadge: '4.9 / 5 — +12.000 RESEÑAS', testimonialsTitle: 'Amado por Usuarios de Todo el Mundo',
    testimonialsSubtitle: 'Únete a miles de clientes satisfechos que confían en VoxVPN para proteger su privacidad cada día.',
    trustedSecure: 'Confiable y Seguro', trustedSubtitle: 'Infraestructura centrada en la privacidad, diseñada para mantenerte protegido',
  },
  fr: {
    home: 'Accueil', features: 'Caractéristiques', servers: 'Serveurs', pricing: 'Tarification',
    support: 'Support', logIn: 'Connexion', signUp: "S'inscrire", choosePlan: 'Choisir un forfait',
    heroTitle: 'Votre Confidentialité. Totalement Protégée.',
    heroSubtitle: "VoxVPN protège votre identité avec un chiffrement de qualité militaire, une politique stricte de non-journalisation et des serveurs ultra-rapides dans plus de 60 pays.",
    getVoxvpn: 'Obtenez VoxVPN Maintenant', seeHowItWorks: "Voir Comment Ça Marche",
    questionsContact: 'Des questions ? Contactez-nous →',
    trustNoLogs: 'Sans Journal', trustAES: 'Chiffrement AES-256', trustLocations: '60+ Emplacements',
    trustKillSwitch: "Coupure d'Urgence", trustMoneyBack: '30 Jours Garantis', trustSupport: 'Support 24/7',
    vpnStatusCard: "Carte d'État VPN", protected: 'Protégé', disconnect: 'Déconnecter', founded: 'Fondée en 2020',
    footerTagline: 'Votre confidentialité est notre priorité. Restez protégé, restez sans restriction.',
    weAccept: 'Nous Acceptons', followUs: 'Suivez-nous',
    footerRights: '© 2026 VoxDigits Communications LLC. Tous droits réservés. www.voxvpn.net',
    footerAbout: 'À Propos', footerContact: 'Contact', footerPrivacy: 'Politique de Confidentialité',
    footerTerms: 'Conditions', footerRefund: 'Politique de Remboursement', footerCookie: 'Politique de Cookies',
    aiAssistant: 'Assistant IA',
    whyVoxvpn: 'Pourquoi VoxVPN', featuresTitle1: 'Tout ce dont vous avez besoin.', featuresTitle2: "Rien que vous n'avez pas.",
    featuresSubtitle: 'Chaque fonctionnalité est conçue dans un seul but : vous garder privé, en sécurité et sans restriction en ligne.',
    readyProtected: 'Prêt à être protégé ?', joinUsers: 'Rejoignez plus de 2 500 utilisateurs qui font confiance à VoxVPN. Plans à partir de 2,49 $/mois.', viewPlans: 'Voir les Forfaits →',
    statServers: 'Serveurs VPN', statServersSub: 'à travers le monde', statCountries: 'Pays', statCountriesSub: 'emplacements de serveurs dans le monde',
    statCustomers: 'Clients Actifs', statCustomersSub: 'protégés dans le monde', statUptime: 'SLA de Disponibilité', statUptimeSub: 'fiabilité garantie',
    globalNetwork: 'Réseau Global', serversTitle1: 'Des Serveurs sur Chaque', serversTitle2: ' Continent',
    serversSubtitle: "Connectez-vous via notre infrastructure haute vitesse dans 20 emplacements sur 4 continents. Chaque serveur exécute VoxVPN avec chiffrement AES-256.",
    totalServers: 'Serveurs Totaux', onlineNow: 'En Ligne', locationsLabel: 'Emplacements', uptimeLabel: 'Disponibilité',
    loadingNetwork: 'Chargement du réseau de serveurs en direct…', loadingMap: 'Chargement de la carte…', regionLocations: 'emplacements', moreLabel: 'plus',
    pricingLabel: 'Tarification', pricingTitle: 'Tarification Simple et Transparente',
    pricingSubtitle: 'Tous les forfaits incluent le chiffrement AES-256 et une stricte politique de non-journalisation. Annulez à tout moment.',
    pricesIn: 'Prix en', detectedLabel: 'Détecté :',
    liveSupport: 'Support client en direct, 24 heures',
    liveSupportDesc: "Un vrai support par de vraies personnes. Nous sommes disponibles par chat en direct et e-mail pour vous aider à configurer et dépanner.",
    contactSupport: 'Contacter le Support →', moneyBackTitle: 'Garantie de remboursement de 30 jours',
    moneyBackDesc: "Notre VPN est facile à utiliser. Notre garantie aussi. Si vous n'êtes pas satisfait, demandez simplement au Support un remboursement complet. Sans tracas, sans risque.",
    getVoxvpnCta: 'Obtenir VoxVPN →', securePayment: 'Paiement Sécurisé par Stripe', pciCompliant: 'Conforme PCI-DSS',
    pricingFooter: 'Tous les prix sont convertis dans votre devise locale ({code}). Garantie de remboursement de 30 jours. Paiement sécurisé via Stripe · Hubtel · Alipay · WeChat Pay.',
    reviewsBadge: '4,9 / 5 — +12 000 AVIS', testimonialsTitle: 'Adoré par les Utilisateurs du Monde Entier',
    testimonialsSubtitle: 'Rejoignez des milliers de clients satisfaits qui font confiance à VoxVPN pour protéger leur vie privée chaque jour.',
    trustedSecure: 'Fiable et Sécurisé', trustedSubtitle: 'Infrastructure axée sur la confidentialité, conçue pour vous garder protégé',
  },
  de: {
    home: 'Startseite', features: 'Funktionen', servers: 'Server', pricing: 'Preisgestaltung',
    support: 'Unterstützung', logIn: 'Anmelden', signUp: 'Registrieren', choosePlan: 'Plan wählen',
    heroTitle: 'Ihre Privatsphäre. Vollständig Geschützt.',
    heroSubtitle: 'VoxVPN schützt Ihre Identität mit militärischer Verschlüsselung, einer strengen No-Logs-Richtlinie und blitzschnellen Servern in über 60 Ländern.',
    getVoxvpn: 'VoxVPN Jetzt Holen', seeHowItWorks: "So Funktioniert's",
    questionsContact: 'Fragen? Kontaktieren Sie uns →',
    trustNoLogs: 'Keine Protokolle', trustAES: 'AES-256-Verschlüsselung', trustLocations: '60+ Standorte',
    trustKillSwitch: 'Kill-Switch', trustMoneyBack: '30 Tage Geld-zurück', trustSupport: '24/7 Support',
    vpnStatusCard: 'VPN-Statuskarte', protected: 'Geschützt', disconnect: 'Trennen', founded: 'Gegründet 2020',
    footerTagline: 'Ihre Privatsphäre ist unsere Priorität. Bleiben Sie geschützt, bleiben Sie unbeschränkt.',
    weAccept: 'Wir Akzeptieren', followUs: 'Folgen Sie Uns',
    footerRights: '© 2026 VoxDigits Communications LLC. Alle Rechte vorbehalten. www.voxvpn.net',
    footerAbout: 'Über Uns', footerContact: 'Kontakt', footerPrivacy: 'Datenschutzrichtlinie',
    footerTerms: 'AGB', footerRefund: 'Rückerstattungsrichtlinie', footerCookie: 'Cookie-Richtlinie',
    aiAssistant: 'KI-Assistent',
    whyVoxvpn: 'Warum VoxVPN', featuresTitle1: 'Alles, was Sie brauchen.', featuresTitle2: 'Nichts, was Sie nicht brauchen.',
    featuresSubtitle: 'Jede Funktion ist auf ein Ziel ausgerichtet: Sie privat, sicher und uneingeschränkt online zu halten.',
    readyProtected: 'Bereit, geschützt zu werden?', joinUsers: 'Treten Sie 2.500+ Nutzern bei, die VoxVPN vertrauen. Pläne ab 2,49 $/Monat.', viewPlans: 'Pläne Ansehen →',
    statServers: 'VPN-Server', statServersSub: 'weltweit', statCountries: 'Länder', statCountriesSub: 'Server-Standorte weltweit',
    statCustomers: 'Aktive Kunden', statCustomersSub: 'weltweit geschützt', statUptime: 'Verfügbarkeits-SLA', statUptimeSub: 'garantierte Zuverlässigkeit',
    globalNetwork: 'Globales Netzwerk', serversTitle1: 'Server auf Jedem', serversTitle2: ' Kontinent',
    serversSubtitle: 'Verbinden Sie sich über unsere Hochgeschwindigkeitsinfrastruktur an 20 Standorten auf 4 Kontinenten. Jeder Server läuft mit VoxVPN und AES-256-Verschlüsselung.',
    totalServers: 'Server Gesamt', onlineNow: 'Jetzt Online', locationsLabel: 'Standorte', uptimeLabel: 'Verfügbarkeit',
    loadingNetwork: 'Live-Servernetzwerk wird geladen…', loadingMap: 'Karte wird geladen…', regionLocations: 'Standorte', moreLabel: 'weitere',
    pricingLabel: 'Preisgestaltung', pricingTitle: 'Einfache, Transparente Preisgestaltung',
    pricingSubtitle: 'Alle Pläne enthalten AES-256-Verschlüsselung und eine strenge No-Logs-Richtlinie. Jederzeit kündbar.',
    pricesIn: 'Preise in', detectedLabel: 'Erkannt:',
    liveSupport: 'Live-Kundensupport, 24 Stunden',
    liveSupportDesc: 'Echter Support von echten Menschen. Wir sind per Live-Chat und E-Mail verfügbar, um Ihnen bei Einrichtung und Fehlerbehebung zu helfen.',
    contactSupport: 'Support Kontaktieren →', moneyBackTitle: '30-Tage-Geld-zurück-Garantie',
    moneyBackDesc: 'Unser VPN ist einfach zu bedienen. Unsere Garantie auch. Wenn Sie nicht zufrieden sind, fordern Sie einfach beim Support eine volle Rückerstattung an. Keine Umstände, kein Risiko.',
    getVoxvpnCta: 'VoxVPN Holen →', securePayment: 'Sichere Zahlung durch Stripe', pciCompliant: 'PCI-DSS-konform',
    pricingFooter: 'Alle Preise werden in Ihre Landeswährung umgerechnet ({code}). 30-Tage-Geld-zurück-Garantie. Sichere Zahlung via Stripe · Hubtel · Alipay · WeChat Pay.',
    reviewsBadge: '4,9 / 5 — 12.000+ BEWERTUNGEN', testimonialsTitle: 'Von Nutzern Weltweit Geliebt',
    testimonialsSubtitle: 'Treten Sie Tausenden zufriedener Kunden bei, die VoxVPN vertrauen, um ihre Privatsphäre täglich zu schützen.',
    trustedSecure: 'Vertrauenswürdig & Sicher', trustedSubtitle: 'Datenschutz-first Infrastruktur, gebaut um Sie zu schützen',
  },
  zh: {
    home: '首页', features: '功能', servers: '服务器', pricing: '定价',
    support: '支持', logIn: '登录', signUp: '注册', choosePlan: '选择计划',
    heroTitle: '您的隐私。全面保护。',
    heroSubtitle: 'VoxVPN 以军用级加密、严格的无日志策略和覆盖60+国家的超快服务器保护您的身份。',
    getVoxvpn: '立即获取 VoxVPN', seeHowItWorks: '查看工作原理',
    questionsContact: '有疑问？联系我们 →',
    trustNoLogs: '无日志政策', trustAES: 'AES-256 加密', trustLocations: '60+ 地区',
    trustKillSwitch: '终止开关', trustMoneyBack: '30天退款保证', trustSupport: '24/7 支持',
    vpnStatusCard: 'VPN 状态卡', protected: '已保护', disconnect: '断开连接', founded: '成立于2020年',
    footerTagline: '您的隐私是我们的首要任务。保持受保护，保持无限制。',
    weAccept: '我们接受', followUs: '关注我们',
    footerRights: '© 2026 VoxDigits Communications LLC. 版权所有. www.voxvpn.net',
    footerAbout: '关于', footerContact: '联系', footerPrivacy: '隐私政策',
    footerTerms: '条款', footerRefund: '退款政策', footerCookie: 'Cookie政策',
    aiAssistant: 'AI助手',
    whyVoxvpn: '为什么选择 VoxVPN', featuresTitle1: '您所需的一切。', featuresTitle2: '无需多余。',
    featuresSubtitle: '每项功能都围绕一个目标设计：让您在线保持隐私、安全和无限制。',
    readyProtected: '准备好获得保护了吗？', joinUsers: '加入2,500+信任VoxVPN的用户。套餐低至$2.49/月。', viewPlans: '查看套餐 →',
    statServers: 'VPN服务器', statServersSub: '遍布全球', statCountries: '国家', statCountriesSub: '全球服务器位置',
    statCustomers: '活跃客户', statCustomersSub: '全球受保护', statUptime: '正常运行SLA', statUptimeSub: '可靠保障',
    globalNetwork: '全球网络', serversTitle1: '覆盖每个', serversTitle2: '大洲的服务器',
    serversSubtitle: '通过我们位于4大洲20个位置的高速基础设施连接。每台服务器均运行VoxVPN并采用AES-256加密。',
    totalServers: '服务器总数', onlineNow: '当前在线', locationsLabel: '位置', uptimeLabel: '正常运行',
    loadingNetwork: '正在加载实时服务器网络…', loadingMap: '正在加载地图…', regionLocations: '个位置', moreLabel: '更多',
    pricingLabel: '定价', pricingTitle: '简单透明的定价',
    pricingSubtitle: '所有套餐均包含AES-256加密和严格的无日志政策。可随时取消。',
    pricesIn: '价格以', detectedLabel: '检测到：',
    liveSupport: '24小时实时客户支持',
    liveSupportDesc: '真人提供真实支持。我们通过实时聊天和电子邮件提供帮助，协助您设置和排查问题。',
    contactSupport: '联系支持 →', moneyBackTitle: '30天退款保证',
    moneyBackDesc: '我们的VPN易于使用，我们的保证同样简单。如果您不满意，只需向支持团队申请全额退款。无麻烦，无风险。',
    getVoxvpnCta: '获取 VoxVPN →', securePayment: 'Stripe安全支付', pciCompliant: '符合PCI-DSS',
    pricingFooter: '所有价格自动换算为您的本地货币（{code}）。30天退款保证。通过Stripe · Hubtel · Alipay · WeChat Pay安全支付。',
    reviewsBadge: '4.9 / 5 — 12,000+ 评价', testimonialsTitle: '深受全球用户喜爱',
    testimonialsSubtitle: '加入数千名满意客户的行列，他们信任VoxVPN每天保护他们的隐私。',
    trustedSecure: '可信与安全', trustedSubtitle: '隐私优先的基础设施，旨在保护您',
  },
  ja: {
    home: 'ホーム', features: '機能', servers: 'サーバー', pricing: '料金',
    support: 'サポート', logIn: 'ログイン', signUp: '登録', choosePlan: 'プランを選択',
    heroTitle: 'あなたのプライバシー。完全に保護。',
    heroSubtitle: 'VoxVPNは軍事級暗号化、厳格なノーログポリシー、60カ国以上の超高速サーバーであなたの身元を保護します。',
    getVoxvpn: '今すぐVoxVPNを入手', seeHowItWorks: '仕組みを見る',
    questionsContact: 'ご質問は？お問い合わせ →',
    trustNoLogs: 'ノーログポリシー', trustAES: 'AES-256暗号化', trustLocations: '60以上のロケーション',
    trustKillSwitch: 'キルスイッチ', trustMoneyBack: '30日返金保証', trustSupport: '24/7サポート',
    vpnStatusCard: 'VPNステータスカード', protected: '保護中', disconnect: '切断', founded: '2020年創業',
    footerTagline: 'あなたのプライバシーが私たちの最優先事項です。保護され、制限なく。',
    weAccept: '対応決済', followUs: 'フォローする',
    footerRights: '© 2026 VoxDigits Communications LLC. All rights reserved. www.voxvpn.net',
    footerAbout: '会社情報', footerContact: 'お問い合わせ', footerPrivacy: 'プライバシーポリシー',
    footerTerms: '利用規約', footerRefund: '返金ポリシー', footerCookie: 'Cookieポリシー',
    aiAssistant: 'AIアシスタント',
    whyVoxvpn: 'VoxVPNが選ばれる理由', featuresTitle1: '必要なすべてを。', featuresTitle2: '不要なものはなし。',
    featuresSubtitle: 'すべての機能は一つの目標で設計されています：あなたをプライベートに、安全に、制限なくオンラインに保つこと。',
    readyProtected: '保護の準備はできましたか？', joinUsers: 'VoxVPNを信頼する2,500以上のユーザーに加わりましょう。プランは$2.49/月から。', viewPlans: 'プランを見る →',
    statServers: 'VPNサーバー', statServersSub: '世界中に', statCountries: 'カ国', statCountriesSub: '世界中のサーバーロケーション',
    statCustomers: 'アクティブユーザー', statCustomersSub: '世界中で保護', statUptime: '稼働率SLA', statUptimeSub: '保証された信頼性',
    globalNetwork: 'グローバルネットワーク', serversTitle1: 'すべての', serversTitle2: '大陸にサーバー',
    serversSubtitle: '4大陸20カ所の高速インフラに接続。全サーバーはAES-256暗号化でVoxVPNを実行。',
    totalServers: 'サーバー総数', onlineNow: '現在オンライン', locationsLabel: 'ロケーション', uptimeLabel: '稼働率',
    loadingNetwork: 'ライブサーバーネットワークを読み込み中…', loadingMap: 'マップを読み込み中…', regionLocations: 'カ所', moreLabel: 'その他',
    pricingLabel: '料金', pricingTitle: 'シンプルで透明な料金',
    pricingSubtitle: 'すべてのプランにAES-256暗号化と厳格なノーログポリシーが含まれます。いつでも解約可能。',
    pricesIn: '表示通貨：', detectedLabel: '検出：',
    liveSupport: '24時間ライブカスタマーサポート',
    liveSupportDesc: '本当のスタッフによる本当のサポート。ライブチャットとメールで設定やトラブルシューティングをサポートします。',
    contactSupport: 'サポートに連絡 →', moneyBackTitle: '30日間返金保証',
    moneyBackDesc: '当社のVPNは使いやすい。保証も同様です。満足できない場合は、サポートに全額返金をリクエストするだけ。面倒なし、リスクなし。',
    getVoxvpnCta: 'VoxVPNを入手 →', securePayment: 'Stripeによる安全な決済', pciCompliant: 'PCI-DSS準拠',
    pricingFooter: 'すべての価格は現地通貨に自動換算されます（{code}）。30日間返金保証。Stripe・Hubtel・Alipay・WeChat Payによる安全な決済。',
    reviewsBadge: '4.9 / 5 — 12,000以上のレビュー', testimonialsTitle: '世界中のユーザーに愛されています',
    testimonialsSubtitle: '毎日プライバシーを守るためVoxVPNを信頼する数千の満足したお客様に加わりましょう。',
    trustedSecure: '信頼と安全', trustedSubtitle: 'プライバシー優先のインフラ、あなたを保護するために構築',
  },
  ru: {
    home: 'Главная', features: 'Возможности', servers: 'Серверы', pricing: 'Цены',
    support: 'Поддержка', logIn: 'Вход', signUp: 'Зарегистрироваться', choosePlan: 'Выбрать план',
    heroTitle: 'Ваша конфиденциальность. Полная защита.',
    heroSubtitle: 'VoxVPN защищает вашу личность с помощью военного шифрования, строгой политики отсутствия журналов и молниеносных серверов в 60+ странах.',
    getVoxvpn: 'Получить VoxVPN Сейчас', seeHowItWorks: 'Как Это Работает',
    questionsContact: 'Вопросы? Свяжитесь с нами →',
    trustNoLogs: 'Без логов', trustAES: 'Шифрование AES-256', trustLocations: '60+ локаций',
    trustKillSwitch: 'Kill Switch', trustMoneyBack: 'Возврат 30 дней', trustSupport: 'Поддержка 24/7',
    vpnStatusCard: 'Карта статуса VPN', protected: 'Защищено', disconnect: 'Отключить', founded: 'Основано в 2020',
    footerTagline: 'Ваша конфиденциальность — наш приоритет. Оставайтесь защищёнными, оставайтесь свободными.',
    weAccept: 'Мы принимаем', followUs: 'Подписывайтесь',
    footerRights: '© 2026 VoxDigits Communications LLC. Все права защищены. www.voxvpn.net',
    footerAbout: 'О нас', footerContact: 'Контакты', footerPrivacy: 'Политика конфиденциальности',
    footerTerms: 'Условия', footerRefund: 'Политика возврата', footerCookie: 'Политика Cookie',
    aiAssistant: 'ИИ-ассистент',
    whyVoxvpn: 'Почему VoxVPN', featuresTitle1: 'Всё, что вам нужно.', featuresTitle2: 'Ничего лишнего.',
    featuresSubtitle: 'Каждая функция создана с одной целью: сохранить вашу конфиденциальность, безопасность и свободу в сети.',
    readyProtected: 'Готовы к защите?', joinUsers: 'Присоединяйтесь к 2 500+ пользователям, доверяющим VoxVPN. Планы от $2.49/мес.', viewPlans: 'Посмотреть Планы →',
    statServers: 'VPN-серверы', statServersSub: 'по всему миру', statCountries: 'Страны', statCountriesSub: 'серверные локации по всему миру',
    statCustomers: 'Активные клиенты', statCustomersSub: 'под защитой по всему миру', statUptime: 'SLA аптайма', statUptimeSub: 'гарантированная надёжность',
    globalNetwork: 'Глобальная сеть', serversTitle1: 'Серверы на каждом', serversTitle2: ' континенте',
    serversSubtitle: 'Подключайтесь через нашу высокоскоростную инфраструктуру в 20 локациях на 4 континентах. Каждый сервер работает на VoxVPN с шифрованием AES-256.',
    totalServers: 'Всего серверов', onlineNow: 'Сейчас онлайн', locationsLabel: 'Локации', uptimeLabel: 'Аптайм',
    loadingNetwork: 'Загрузка сети серверов в реальном времени…', loadingMap: 'Загрузка карты…', regionLocations: 'локаций', moreLabel: 'ещё',
    pricingLabel: 'Цены', pricingTitle: 'Простые и прозрачные цены',
    pricingSubtitle: 'Все планы включают шифрование AES-256 и строгую политику отсутствия журналов. Отмена в любое время.',
    pricesIn: 'Цены в', detectedLabel: 'Определено:',
    liveSupport: 'Живая поддержка клиентов 24 часа',
    liveSupportDesc: 'Настоящая поддержка от настоящих людей. Мы доступны через живой чат и электронную почту, чтобы помочь с настройкой и решением проблем.',
    contactSupport: 'Связаться с поддержкой →', moneyBackTitle: 'Гарантия возврата 30 дней',
    moneyBackDesc: 'Наш VPN прост в использовании. Как и наша гарантия. Если вы не удовлетворены, просто попросите поддержку о полном возврате. Без хлопот, без риска.',
    getVoxvpnCta: 'Получить VoxVPN →', securePayment: 'Безопасная оплата через Stripe', pciCompliant: 'Соответствие PCI-DSS',
    pricingFooter: 'Все цены автоматически конвертируются в вашу валюту ({code}). Гарантия возврата 30 дней. Безопасная оплата через Stripe · Hubtel · Alipay · WeChat Pay.',
    reviewsBadge: '4,9 / 5 — 12 000+ ОТЗЫВОВ', testimonialsTitle: 'Любим пользователями по всему миру',
    testimonialsSubtitle: 'Присоединяйтесь к тысячам довольных клиентов, которые доверяют VoxVPN защищать их конфиденциальность каждый день.',
    trustedSecure: 'Надёжно и безопасно', trustedSubtitle: 'Инфраструктура с приоритетом конфиденциальности, созданная для вашей защиты',
  },
  ar: {
    home: 'الرئيسية', features: 'الميزات', servers: 'الخوادم', pricing: 'التسعير',
    support: 'الدعم', logIn: 'تسجيل الدخول', signUp: 'التسجيل', choosePlan: 'اختر خطة',
    heroTitle: 'خصوصيتك. محمية بالكامل.',
    heroSubtitle: 'يحمي VoxVPN هويتك بتشفير عسكري، وسياسة صارمة لعدم حفظ السجلات، وخوادم فائقة السرعة في أكثر من 60 دولة.',
    getVoxvpn: 'احصل على VoxVPN الآن', seeHowItWorks: 'شاهد كيف يعمل',
    questionsContact: 'أسئلة؟ تواصل معنا ←',
    trustNoLogs: 'بدون سجلات', trustAES: 'تشفير AES-256', trustLocations: '+60 موقعًا',
    trustKillSwitch: 'مفتاح الإيقاف', trustMoneyBack: 'استرداد خلال 30 يومًا', trustSupport: 'دعم 24/7',
    vpnStatusCard: 'بطاقة حالة VPN', protected: 'محمي', disconnect: 'قطع الاتصال', founded: 'تأسس 2020',
    footerTagline: 'خصوصيتك هي أولويتنا. ابقَ محميًا، ابقَ بلا قيود.',
    weAccept: 'نقبل', followUs: 'تابعنا',
    footerRights: '© 2026 VoxDigits Communications LLC. جميع الحقوق محفوظة. www.voxvpn.net',
    footerAbout: 'من نحن', footerContact: 'اتصل بنا', footerPrivacy: 'سياسة الخصوصية',
    footerTerms: 'الشروط', footerRefund: 'سياسة الاسترداد', footerCookie: 'سياسة ملفات تعريف الارتباط',
    aiAssistant: 'مساعد الذكاء الاصطناعي',
    whyVoxvpn: 'لماذا VoxVPN', featuresTitle1: 'كل ما تحتاجه.', featuresTitle2: 'لا شيء لا تحتاجه.',
    featuresSubtitle: 'كل ميزة مصممة لهدف واحد: إبقائك خاصًا وآمنًا وغير مقيد عبر الإنترنت.',
    readyProtected: 'هل أنت مستعد للحماية؟', joinUsers: 'انضم إلى أكثر من 2,500 مستخدم يثقون بـ VoxVPN. الخطط تبدأ من $2.49/شهر.', viewPlans: 'عرض الخطط ←',
    statServers: 'خوادم VPN', statServersSub: 'حول العالم', statCountries: 'دولة', statCountriesSub: 'مواقع الخوادم حول العالم',
    statCustomers: 'عملاء نشطون', statCustomersSub: 'محميون حول العالم', statUptime: 'اتفاقية تشغيل', statUptimeSub: 'موثوقية مضمونة',
    globalNetwork: 'شبكة عالمية', serversTitle1: 'خوادم في كل', serversTitle2: ' قارة',
    serversSubtitle: 'اتصل عبر بنيتنا التحتية عالية السرعة في 20 موقعًا عبر 4 قارات. كل خادم يعمل بـ VoxVPN مع تشفير AES-256.',
    totalServers: 'إجمالي الخوادم', onlineNow: 'متصل الآن', locationsLabel: 'المواقع', uptimeLabel: 'التشغيل',
    loadingNetwork: 'جارٍ تحميل شبكة الخوادم المباشرة…', loadingMap: 'جارٍ تحميل الخريطة…', regionLocations: 'مواقع', moreLabel: 'المزيد',
    pricingLabel: 'التسعير', pricingTitle: 'تسعير بسيط وشفاف',
    pricingSubtitle: 'جميع الخطط تشمل تشفير AES-256 وسياسة صارمة لعدم حفظ السجلات. ألغِ في أي وقت.',
    pricesIn: 'الأسعار بـ', detectedLabel: 'تم اكتشاف:',
    liveSupport: 'دعم عملاء مباشر على مدار الساعة',
    liveSupportDesc: 'دعم حقيقي من أشخاص حقيقيين. نحن متاحون عبر الدردشة المباشرة والبريد الإلكتروني لمساعدتك في الإعداد وحل المشكلات.',
    contactSupport: 'تواصل مع الدعم ←', moneyBackTitle: 'ضمان استرداد لمدة 30 يومًا',
    moneyBackDesc: 'خدمة VPN لدينا سهلة الاستخدام. وضماننا كذلك أيضًا. إذا لم تكن راضيًا، فقط اطلب من الدعم استردادًا كاملاً. بلا متاعب، بلا مخاطر.',
    getVoxvpnCta: 'احصل على VoxVPN ←', securePayment: 'دفع آمن عبر Stripe', pciCompliant: 'متوافق مع PCI-DSS',
    pricingFooter: 'جميع الأسعار تُحوَّل تلقائيًا إلى عملتك المحلية ({code}). ضمان استرداد لمدة 30 يومًا. دفع آمن عبر Stripe · Hubtel · Alipay · WeChat Pay.',
    reviewsBadge: '4.9 / 5 — +12,000 تقييم', testimonialsTitle: 'محبوب من المستخدمين حول العالم',
    testimonialsSubtitle: 'انضم إلى آلاف العملاء الراضين الذين يثقون بـ VoxVPN لحماية خصوصيتهم كل يوم.',
    trustedSecure: 'موثوق وآمن', trustedSubtitle: 'بنية تحتية تركز على الخصوصية، مصممة لحمايتك',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    // Respect a previously saved manual choice
    const saved = localStorage.getItem('voxvpn_language');
    if (saved && translations[saved]) {
      setLanguage(saved);
      return;
    }
    // No saved preference — detect from the visitor's IP (once)
    let cancelled = false;
    base44.functions.invoke('detectLanguageByIp', {})
      .then((res) => {
        const data = res?.data || res;
        const detected = data?.language;
        if (!cancelled && detected && translations[detected]) {
          setLanguage(detected);
          localStorage.setItem('voxvpn_language', detected);
        }
      })
      .catch(() => { /* fall back to English silently */ });
    return () => { cancelled = true; };
  }, []);

  // Sync <html lang> and text direction (RTL for Arabic) whenever language changes
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('voxvpn_language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}